In [55]:
import numpy as np

In [56]:
import pandas as pd

In [57]:
matrix_x = np.array ([[1, 0.2,0.5], [0.2,1,0.8],[0.5, 0.8 ,1]])
print(matrix_x)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


# I )

In [58]:
matrix_x.T                      #changing the rows into columns 

array([[1. , 0.2, 0.5],
       [0.2, 1. , 0.8],
       [0.5, 0.8, 1. ]])

# ii )

In [59]:
matrix_det = np.linalg.det(matrix_x)
print(matrix_det)

0.2299999999999999


# iv)

In [60]:
matrix_x.shape

(3, 3)

In [68]:
new_matrix = np.hstack(matrix_x,(1,2,3),(x=0))

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (249774313.py, line 1)